configured lifespan
marikudes/calc pull request #12
Opened 2024-09-23 18:14 UTC by marikudes

2024-09-23 20:52 UTC, Resheba requested changes

2024-09-23 20:52 UTC, Resheba commented on src/main.py
>  app.include_router(calc_router, prefix="")
include внутрь lifespan

2024-09-23 20:52 UTC, Resheba commented on src/main.py
> +    yield
В `yield` возвращай dict с state.
https://www.starlette.io/lifespan/

2024-09-25 20:21 UTC, marikudes commented on src/main.py
>  app.include_router(calc_router, prefix="")
сделано

2024-09-25 20:21 UTC, marikudes commented on src/main.py
> +    yield
готово

2024-09-26 08:45 UTC, Resheba requested changes

2024-09-26 08:45 UTC, Resheba commented on src/main.py
> +    yield {"state": app.state}
Лучше это по другому использовать.)
Вот хороший пример из доки:
https://www.starlette.io/lifespan/

2024-09-29 00:20 UTC, marikudes commented on src/main.py
> +    yield {"state": app.state}
обновил

2024-09-29 12:04 UTC, Resheba commented on src/main.py
> +        yield {"http_client": client}
Зачем тебе httpx Клиент? Где он используется?

2024-09-29 12:11 UTC, Resheba requested changes

2024-09-29 12:11 UTC, Resheba commented on src/main.py
> +        yield {"http_client": client}
Тебе нужно в State передать Jinja instance. State - это пространство общее для всего приложения.
То есть, если у тебя есть объекты общие для всего приложения (Stateful app), их можно держать в state.

2024-09-29 12:11 UTC, Resheba commented on src/main.py
> +        yield {"http_client": client}
Вот пример:
```suggestion
    yield {"jinja": Jinja2Templates(directory=templates_dir)}
```

2024-10-01 21:51 UTC, Resheba requested changes

2024-10-01 21:51 UTC, Resheba commented on src/routers/calc/router.py
> +    templates: Jinja2Templates = request.app.state.templates
```suggestion
    templates: Jinja2Templates = request.state
```

2024-10-01 21:51 UTC, Resheba commented on src/main.py
> +    app.state.templates = Jinja2Templates(
Это теперь удалёям.
Рефакторни все моменты связанные с state. Чтобы не было проблем.

2024-10-03 11:48 UTC, Resheba approved these changes

2024-10-03 12:22 UTC, merged